client_id = "fda671a4e0240330eb9e10b8af1a9061"
name = "Post SEO"
application_url = "https://post-seo.test/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gazelle-app-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,read_products,write_products,read_customers,write_customers,write_orders,write_draft_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://post-seo.test/authenticate"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false